# -*- coding: utf-8 -*-
"""cleaning_day2(1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19XO8xRUrJmuLlzbL3ES_LKX5dT-AejxP
"""

import pandas as pd

df = pd.read_csv('/content/retail_day1.csv')

#Display original dataszet info

print("FIRST 5 ROWS")
print(df.head())

print("\nDATA TYPES BEFORE CONVERSION")
print(df.dtypes)

print("\nDATASET SHAPE BEFORE REMOVING DUPLICATES")
print(df.shape)

# Check duplicate rows
print("\nNUMBER OF DUPLICATE ROWS")
print(df.duplicated().sum())

# Remove duplicates
df = df.drop_duplicates()

print("\nDATASET SHAPE AFTER REMOVING DUPLICATES")
print(df.shape)

# Check current data types
print("\nCURRENT DATA TYPES:")
print(df.dtypes)

# Convert InvoiceDate column to datetime
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

# Convert CustomerID to integer
df['CustomerID'] = df['CustomerID'].astype(float).astype('Int64')

# Check updated data types
print("\nDATA TYPES AFTER CONVERSION")
print(df.dtypes)

print("\nFINAL CLEANED DATASET:")
print(df.head())

df.to_csv('retail_day2(1).csv', index=False)

print("\nCleaned dataset saved as 'retail_day2(1).csv'")