# -*- coding: utf-8 -*-
"""cleaning_day3(1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iIWsfSqwbRAgakJZzi9SbIlEGY718qoh
"""

import pandas as pd

df = pd.read_csv('/content/retail_day2(1) (1).csv')

print("FIRST 5 ROWS")
print(df.head())

print("\nDATASET SHAPE BEFORE CLEANING")
print(df.shape)

#Remove Invalid Quantities (Quantity > 0)
#Remove Invalid Prices (UnitPrice > 0)
df_cleaned = df[(df['Quantity'] > 0) & (df['UnitPrice'] > 0)]

print(f"Cleaned dataset shape: {df_cleaned.shape}")
print(f"Total rows removed: {len(df) - len(df_cleaned)}")

# Quantity less than or equal to 0
invalid_quantity = df[df['Quantity'] <= 0]

print("\nINVALID QUANTITY ROWS")
print(invalid_quantity.head())

print("\nNUMBER OF INVALID QUANTITY ROWS")
print(invalid_quantity.shape[0])

#Remove invalid quantites

df = df[df['Quantity'] > 0]

print("\nDATASET SHAPE AFTER REMOVING INVALID QUANTITIES")
print(df.shape)

# UnitPrice less than or equal to 0
invalid_price = df[df['UnitPrice'] <= 0]

print("\nINVALID PRICE ROWS")
print(invalid_price.head())

print("\nNUMBER OF INVALID PRICE ROWS")
print(invalid_price.shape[0])

print("\nCLEANED DATASET PREVIEW")
print(df.head())

print("\nCHECK REMAINING INVALID QUANTITIES")
print((df['Quantity'] <= 0).sum())

print("\nCHECK REMAINING INVALID PRICES")
print((df['UnitPrice'] <= 0).sum())

# Save cleaned dataset as CSV file
df.to_csv('retail_day3(1).csv', index=False)

print("Dataset saved successfully!")