# -*- coding: utf-8 -*-
"""cleaning_day2(2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w3p2PSs04kKYBGAIxHx4Y2utXjub6D6G
"""

import pandas as pd

df = pd.read_csv('/content/retail_day2(1) (1).csv')

print("FIRST 5 ROWS")
print(df.head())

print("\nDATASET SHAPE BEFORE REMOVING CANCELLED ORDERS")
print(df.shape)

# In this dataset, cancelled invoices start with 'C'

cancelled_orders = df[df['InvoiceNo'].astype(str).str.startswith('C')]

print("\nNUMBER OF CANCELLED ORDERS")
print(cancelled_orders.shape[0])

print("\nCANCELLED ORDERS SAMPLE")
print(cancelled_orders.head())

# Keep only non-cancelled orders
df = df[~df['InvoiceNo'].astype(str).str.startswith('C')]

print("\nDATASET SHAPE AFTER REMOVING CANCELLED ORDERS")
print(df.shape)

# Check if any cancelled orders still exist
remaining_cancelled = df[df['InvoiceNo'].astype(str).str.startswith('C')]

print("\nREMAINING CANCELLED ORDERS")
print(remaining_cancelled.shape[0])

print("\nCLEANED DATASET PREVIEW")
print(df.head())

df.to_csv('retail_day2(2).csv', index=False)

print("\nCleaned dataset saved as 'retail_day2(2).csv'")