# -*- coding: utf-8 -*-
"""cleaning_day4(3).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R87mXQanAb_ohEuZCxx8nUTaKjo_sd4O
"""

import pandas as pd

df = pd.read_csv('/content/retail_day4(1).csv')\

print("FIRST 5 ROWS")
print(df.head())

print("\nDATASET SHAPE")
print(df.shape)

#Convert InvoiceDate to DateTime

print("FIRST 5 ROWS")
print(df.head())

print("\nDATASET SHAPE")
print(df.shape)

import pandas as pd

#Create new useful columns

# Convert InvoiceDate to DateTime if not already converted
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

# Create TotalPrice column
df['TotalPrice'] = df['Quantity'] * df['UnitPrice']

# Create Year column
df['Year'] = df['InvoiceDate'].dt.year

# Create Month column
df['Month'] = df['InvoiceDate'].dt.month

# Create Day column
df['Day'] = df['InvoiceDate'].dt.day

# Create Day Name column
df['DayName'] = df['InvoiceDate'].dt.day_name()

# Create Hour column
df['Hour'] = df['InvoiceDate'].dt.hour

print("\nDATASET WITH NEW COLUMNS")
print(df.head())

print("\nNEW COLUMN NAMES")
print(df.columns)

#Final Dataset Summary

print("\nFINAL DATASET SUMMARY")
print(df.info())

print("\nSTATISTICAL SUMMARY")
print(df.describe())

print("\nMISSING VALUES")
print(df.isnull().sum())

print("\nDUPLICATE ROWS")
print(df.duplicated().sum())

print("\nFINAL DATASET SHAPE")
print(df.shape)

df.to_csv('final_cleaned_retail_dataset.csv', index=False)
print("\nFINAL CLEANED DATASET SAVED SUCCESSFULLY!")

