# -*- coding: utf-8 -*-
"""cleaning_day4(2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ViarJeZ4OKTxASuKOtSmIRegqsXKEqHP
"""

import pandas as pd

df = pd.read_csv('/content/retail_day3(2).csv')

print("FIRST 5 ROWS")
print(df.head())

print("\nCOLUMN NAMES BEFORE REMOVING")
print(df.columns)

print("\nDATASET SHAPE BEFORE REMOVING COLUMNS")
print(df.shape)

# Replace column names if needed

columns_to_remove = ['index']

# Remove columns
df = df.drop(columns=columns_to_remove, errors='ignore')

print("\nCOLUMN NAMES AFTER REMOVING")
print(df.columns)

print("\nDATASET SHAPE AFTER REMOVING COLUMNS")
print(df.shape)

print("\nCLEANED DATASET PREVIEW")
print(df.head())

df.to_csv('retail_day4(1).csv', index=False)

print("\nCLEANED DATASET SAVED SUCCESSFULLY!")