# -*- coding: utf-8 -*-
"""cleaning_day3(2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ovKJaoIkZ_9wCoxqijIJeVfav_6-nLXQ
"""

import pandas as pd
import numpy as np

df = pd.read_csv('/content/retail_day3(1).csv')

print("FIRST 5 ROWS")
print(df.head())

print("\nDATASET SHAPE BEFORE CLEANING")
print(df.shape)

#standardize text data

# Remove extra spaces
df['Description'] = df['Description'].astype(str).str.strip()

# Convert Description to uppercase
df['Description'] = df['Description'].str.upper()

# Remove extra spaces and standardize Country column
df['Country'] = df['Country'].astype(str).str.strip().str.upper()

print("\nSTANDARDIZED TEXT DATA")
print(df[['Description', 'Country']].head())

#Detect outliners

# Detect outliers in Quantity column
Q1_quantity = df['Quantity'].quantile(0.25)
Q3_quantity = df['Quantity'].quantile(0.75)
IQR_quantity = Q3_quantity - Q1_quantity

lower_quantity = Q1_quantity - 1.5 * IQR_quantity
upper_quantity = Q3_quantity + 1.5 * IQR_quantity

print("\nQUANTITY OUTLIER RANGE")
print("Lower Limit:", lower_quantity)
print("Upper Limit:", upper_quantity)

# Detect outliers in UnitPrice column
Q1_price = df['UnitPrice'].quantile(0.25)
Q3_price = df['UnitPrice'].quantile(0.75)
IQR_price = Q3_price - Q1_price

lower_price = Q1_price - 1.5 * IQR_price
upper_price = Q3_price + 1.5 * IQR_price

print("\nUNIT PRICE OUTLIER RANGE")
print("Lower Limit:", lower_price)
print("Upper Limit:", upper_price)

#Display outliners

quantity_outliers = df[
    (df['Quantity'] < lower_quantity) |
    (df['Quantity'] > upper_quantity)
]

price_outliers = df[
    (df['UnitPrice'] < lower_price) |
    (df['UnitPrice'] > upper_price)
]

print("\nNUMBER OF QUANTITY OUTLIERS")
print(quantity_outliers.shape[0])

print("\nNUMBER OF PRICE OUTLIERS")
print(price_outliers.shape[0])

#Remove outliners

df = df[
    (df['Quantity'] >= lower_quantity) &
    (df['Quantity'] <= upper_quantity)
]

df = df[
    (df['UnitPrice'] >= lower_price) &
    (df['UnitPrice'] <= upper_price)
]

print("\nDATASET SHAPE AFTER REMOVING OUTLIERS")
print(df.shape)

print("\nCLEANED DATASET PREVIEW")
print(df.head())

df.to_csv('retail_day3(2).csv', index=False)

print("\nCLEANED DATASET SAVED SUCCESSFULLY!")

