# -*- coding: utf-8 -*-
"""cleaning_day1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xiIzla-rClkBD1hcqSxuBHDCVMcuXrBs
"""

import pandas as pd
import numpy as np

df = pd.read_csv('/content/online_retail.csv')

# Display first 5 rows
print("FIRST 5 ROWS")
print(df.head())

# Display last 5 rows
print("\nLAST 5 ROWS")
print(df.tail())

# Dataset shape
print("\nDATASET SHAPE")
print(df.shape)

# Column names
print("\nCOLUMN NAMES")
print(df.columns)

# Data types
print("\nDATA TYPES")
print(df.dtypes)

# General information
print("\nDATASET INFO")
print(df.info())

# Statistical summary
print("\nSTATISTICAL SUMMARY")
print(df.describe())

# Count missing values
print("\nMISSING VALUES")
print(df.isnull().sum())

# Percentage of missing values
print("\nPERCENTAGE OF MISSING VALUES")
print((df.isnull().sum() / len(df)) * 100)

# Display rows containing missing values
print("\nROWS WITH MISSING VALUES")
print(df[df.isnull().any(axis=1)])

# Fill missing values in Description column
df['Description'] = df['Description'].fillna('Unknown')

# Remove rows where CustomerID is missing
df = df.dropna(subset=['CustomerID'])

print("\nMISSING VALUES AFTER CLEANING")
print(df.isnull().sum())

print("\nCLEANED DATASET PREVIEW")
print(df.head())

print("\nFINAL DATASET SHAPE")
print(df.shape)

print("Missing values:",df.isnull().sum().sum())

print("Duplicates:",df.duplicated().sum())

df.to_csv('retail_day1.csv',index=False)
print("Day 1 checkpoint saved as retail_day1.csv!")