# -*- coding: utf-8 -*-
"""week2(4).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11k-G9DgLHf9_9I_miTjzCL-iMPOBr0a7
"""

import pandas as pd

# Load dataset
df = pd.read_csv('/content/validated_retail_dataset.csv')

# Preview columns
print(df.columns)

#Create Quantity Categories
quantity_bins = [0, 5, 20, 1000]
quantity_labels = ['Low', 'Medium', 'High']

df['Quantity_Category'] = pd.cut(
    df['quantity'], # Changed 'Quantity' to 'quantity'
    bins=quantity_bins,
    labels=quantity_labels
)

# Create Unit Price Categories
price_bins = [0, 2, 5, 1000]
price_labels = ['Cheap', 'Moderate', 'Expensive']

df['Price_Category'] = pd.cut(
    df['unitprice'], # Changed 'UnitPrice' to 'unitprice'
    bins=price_bins,
    labels=price_labels
)

# Display sample
print(df[['quantity', 'Quantity_Category',
          'unitprice', 'Price_Category']].head()) # Changed 'Quantity' to 'quantity' and 'UnitPrice' to 'unitprice'

# Save updated dataset
df.to_csv('binned_retail_dataset.csv', index=False)

print("Categories/Bins created successfully!")
print("Updated dataset saved as 'binned_retail_dataset.csv'")