# -*- coding: utf-8 -*-
"""week2(1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H5HuXtmvMvvNjvSpV_5F1BM8_SyRfEJ6
"""

import pandas as pd

df = pd.read_csv('/content/final_cleaned_retail_dataset.csv')

print("ORIGINAL COLUMN NAMES")
print(df.columns)

# Convert column names to lowercase
# Replace spaces with underscore

df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

# Select all text/object columns
text_columns = df.select_dtypes(include='object').columns

# Remove extra spaces
for col in text_columns:
    df[col] = df[col].astype(str).str.strip()

print("\nUPDATED COLUMN NAMES")
print(df.columns)

print("\nDATASET PREVIEW")
print(df.head())

df.to_csv('retail_dataset_cleaned_v2.csv', index=False)

print("\nUPDATED DATASET SAVED SUCCESSFULLY!")

