# -*- coding: utf-8 -*-
"""week2(2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-jnlrgY4a65vyoSb0OTksZ4uJQbs_R2K
"""

import pandas as pd

# Try to read the CSV, skipping bad lines and using the 'python' engine
df = pd.read_csv('/content/retail_cleaned_v2.csv', on_bad_lines='skip', engine='python')

print("FIRST 5 ROWS")
print(df.head())

#select  text columns
text_columns = df.select_dtypes(include='object').columns

print("\nTEXT COLUMNS")
print(text_columns)

# Convert all text to uppercase
for col in text_columns:
    df[col] = df[col].astype(str).str.upper()

# Remove special characters from text columns
for col in text_columns:
    df[col] = df[col].str.replace(r'[^A-Z0-9 ]', '', regex=True)

print("\nCLEANED DATASET PREVIEW")
print(df.head())

df.to_csv('retail_cleaned.csv', index=False)

print("\nFINAL CLEANED DATASET SAVED SUCCESSFULLY!")