# -*- coding: utf-8 -*-
"""week2(5).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wKxU8TC4bsZ3_lpoTrOTGIez1R7i528T
"""

import pandas as pd
from sklearn.preprocessing import StandardScaler, LabelEncoder

# Load dataset
df = pd.read_csv('/content/binned_retail_dataset.csv')

#Scale numerical columns
numerical_cols = ['Quantity', 'UnitPrice', 'TotalPrice']

scaler = StandardScaler()

df[numerical_cols] = scaler.fit_transform(df[numerical_cols])

print("Numerical columns scaled successfully")

#Encode categorical columns

categorical_cols = df.select_dtypes(include=['object', 'category']).columns

label_encoder = LabelEncoder()

for col in categorical_cols:
    df[col] = label_encoder.fit_transform(df[col].astype(str))

print("Categorical columns encoded successfully")

# Display updated dataset
print(df.head())

# Save updated dataset
df.to_csv('scaled_encoded_retail_dataset.csv', index=False)

print("Updated dataset saved as scaled_encoded_retail_dataset.csv")