# -*- coding: utf-8 -*-
"""week3(4).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lK21JB1Ocd5JH6mXM4Wp9wFNJRxQDzNk
"""

import pandas as pd

# Load dataset
df = pd.read_csv('/content/valid_retail_dataset.csv')

#Detect and remove outliners

# Detect outliers in Quantity and UnitPrice using IQR method
for col in ['Quantity', 'UnitPrice']:
    if col in df.columns:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1

        lower_limit = Q1 - 1.5 * IQR
        upper_limit = Q3 + 1.5 * IQR

        df = df[(df[col] >= lower_limit) & (df[col] <= upper_limit)]

print("Shape after removing outliers:", df.shape)

#Standardize text data

# Select text columns
text_cols = df.select_dtypes(include=['object']).columns

# Remove extra spaces and convert text to uppercase
for col in text_cols:
    df[col] = df[col].astype(str).str.strip().str.upper()

print("Text data standardized successfully!")

# Save updated dataset
df.to_csv('outlier_text_cleaned_dataset.csv', index=False)

print("Updated dataset saved successfully!")