# -*- coding: utf-8 -*-
"""week3(3).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1veSYsfhQ7g_yj6NgO9wjLCeg-CErAdD-
"""

import pandas as pd

# Load dataset
df = pd.read_csv('/content/updated_retail_dataset.csv')

#Remove invalid quantities

# Keep only rows where Quantity > 0
if 'Quantity' in df.columns:
    df = df[df['Quantity'] > 0]

print("Shape after removing invalid quantities:", df.shape)

#Remove invalid prices

# Keep only rows where UnitPrice > 0
if 'UnitPrice' in df.columns:
    df = df[df['UnitPrice'] > 0]

print("Shape after removing invalid prices:", df.shape)

# Save cleaned dataset
df.to_csv('valid_retail_dataset.csv', index=False)

print("\nDataset with valid quantities and prices saved successfully!")



