# -*- coding: utf-8 -*-
"""week2(3).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zfTDZ9eRjj43ca2WwiS8K_C4ZjaLeq55
"""

import pandas as pd

df = pd.read_csv('/content/retail_cleaned_v2 (1).csv')

print("FIRST 5 ROWS")
print(df.head())

# Create calculated TotalPrice
df['Calculated_TotalPrice'] = df['quantity'] * df['unitprice']

# Find inconsistent rows
inconsistent_rows = df[
    df['totalprice'] != df['Calculated_TotalPrice']
]

print("\nNUMBER OF INCONSISTENT ROWS")
print(inconsistent_rows.shape[0])

print("\nINCONSISTENT ROWS")
print(inconsistent_rows.head())

df['totalprice'] = df['quantity'] * df['unitprice']

# Remove temporary column
df.drop('Calculated_TotalPrice', axis=1, inplace=True, errors='ignore')

print("\nTOTALPRICE VALIDATED SUCCESSFULLY")

print("\nUPDATED DATASET PREVIEW")
print(df.head())

df.to_csv('validated_retail_dataset.csv', index=False)

print("\nVALIDATED DATASET SAVED SUCCESSFULLY!")