# -*- coding: utf-8 -*-
"""Week4(2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qJs0q0KaSGaPMf0dRXj_YAqqyFjhYi9u
"""

import pandas as pd

# Load dataset
df = pd.read_csv('/content/validated_dataset.csv')

#Create new useful columns
# Convert invoice date to datetime
df['invoicedate'] = pd.to_datetime(df['invoicedate'], errors='coerce')

# Create date-based columns
df['year'] = df['invoicedate'].dt.year
df['month'] = df['invoicedate'].dt.month
df['day'] = df['invoicedate'].dt.day
df['dayname'] = df['invoicedate'].dt.day_name()
df['hour'] = df['invoicedate'].dt.hour

# Create revenue column
df['revenue'] = df['quantity'] * df['unitprice']

print("New useful columns created successfully.")

#Create categories bins
# Quantity categories
df['quantity_category'] = pd.cut(
    df['quantity'],
    bins=[0, 5, 20, max(20.0000001, df['quantity'].max())],
    labels=['Low Quantity', 'Medium Quantity', 'High Quantity']
)

# Price categories
df['price_category'] = pd.cut(
    df['unitprice'],
    bins=[0, 2, 10, max(10.0000001, df['unitprice'].max())],
    labels=['Low Price', 'Medium Price', 'High Price']
)

# Revenue categories
df['revenue_category'] = pd.cut(
    df['revenue'],
    bins=[0, 20, 100, max(100.0000001, df['revenue'].max())],
    labels=['Low Revenue', 'Medium Revenue', 'High Revenue']
)

print("Categories/Bins created successfully.")

# Save updated dataset
df.to_csv('new_columns_binned_dataset.csv', index=False)

print("Dataset saved as new_columns_binned_dataset.csv")

