# -*- coding: utf-8 -*-
"""Week4(4).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fAJWo7F-Pd7DhGcYIy59CjOZ9E11PT7q
"""

import pandas as pd

df = pd.read_csv("/content/scaled_encoded_dataset.csv")

# 1. Remove Unnecessary Columns
# Remove columns that are not needed for ML/modeling
columns_to_remove = ["invoiceno", "invoicedate"]

df = df.drop(columns=columns_to_remove, errors="ignore")

print("Columns after removing unnecessary columns:")
print(df.columns)

# 2. Check Data Consistency

# Check missing values
print("Missing values:")
print(df.isnull().sum())

# Check duplicate rows
print("Duplicate rows:", df.duplicated().sum())

# Check if revenue and totalprice are same
if "revenue" in df.columns and "totalprice" in df.columns:
    inconsistent_rows = df[df["revenue"] != df["totalprice"]]
    print("Inconsistent revenue rows:", len(inconsistent_rows))

# Check data types
print("Data types:")
print(df.dtypes)

# 3. Handle Imbalanced Data

# Example: using revenue_category as target column
target_column = "revenue_category"

print("Before balancing:")
print(df[target_column].value_counts())

# Separate majority and minority classes
min_count = df[target_column].value_counts().min()

balanced_df = (
    df.groupby(target_column)
    .sample(n=min_count, random_state=42)
    .reset_index(drop=True)
)

print("After balancing:")
print(balanced_df[target_column].value_counts())

# Save the final dataset
balanced_df.to_csv("final_balanced_dataset.csv", index=False)

print("Final balanced dataset saved successfully!")