# -*- coding: utf-8 -*-
"""Week4(3).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1riLo9Ish8mGcUQAGn6_DI3zm61FYzTP0
"""

import pandas as pd
from sklearn.preprocessing import StandardScaler, LabelEncoder

df = pd.read_csv("/content/new_columns_binned_dataset.csv")

#Scale numerical columns

numerical_cols = [
    'quantity', 'unitprice', 'totalprice',
    'year', 'month', 'day', 'hour', 'revenue'
]

scaler = StandardScaler()

df[numerical_cols] = scaler.fit_transform(df[numerical_cols])

print("Numerical columns scaled successfully")
print(df[numerical_cols].head())

#Encode categorical columns

categorical_cols = [
    'dayname',
    'quantity_category',
    'price_category',
    'revenue_category'
]

label_encoder = LabelEncoder()

for col in categorical_cols:
    df[col] = label_encoder.fit_transform(df[col])

print("Categorical columns encoded successfully")
print(df[categorical_cols].head())

#Save dataset

df.to_csv("scaled_encoded_dataset.csv", index=False)

print("Updated dataset saved as scaled_encoded_dataset.csv")

