# -*- coding: utf-8 -*-
"""week3(5).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wCVwjXl7rZ3Ff-2jzUVSdpkQTFVxBuvm
"""

import pandas as pd
import re

# Load dataset
df = pd.read_csv('/content/outlier_text_cleaned_dataset.csv')

#Remove special character

# Remove special characters from all text columns
text_cols = df.select_dtypes(include=['object']).columns

for col in text_cols:
    df[col] = df[col].astype(str).apply(
        lambda x: re.sub(r'[^A-Za-z0-9\s]', '', x)
    )

print("Special characters removed successfully!")

#Rename columns

# Convert column names to lowercase and replace spaces with underscores
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(' ', '_')
)

print("\nUpdated Column Names:")
print(df.columns.tolist())

# Save updated dataset
df.to_csv('specialchar_renamed_dataset.csv', index=False)

print("\nDataset saved successfully!")