# -*- coding: utf-8 -*-
"""Week4(1)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/179Ph8M6Mf1ig8pi2fp6CJc8jeQqcESqk
"""

import pandas as pd

# Load dataset
df = pd.read_csv('/content/specialchar_renamed_dataset.csv')

# Remove extra spaces from column names
df.columns = df.columns.str.strip()

# Remove leading/trailing spaces and multiple spaces in text columns
text_cols = df.select_dtypes(include='object').columns

for col in text_cols:
    df[col] = df[col].astype(str).str.strip()  # remove leading/trailing spaces
    df[col] = df[col].str.replace(r'\s+', ' ', regex=True)  # replace multiple spaces with single space

print("Extra spaces removed successfully.")

# Create calculated total price
df['calculated_totalprice'] = df['quantity'] * df['unitprice']

# Compare with existing TotalPrice column
df['totalprice_match'] = (
    round(df['totalprice'], 2) ==
    round(df['calculated_totalprice'], 2)
)

# Display mismatched records
mismatches = df[df['totalprice_match'] == False]

print(f"\nNumber of inconsistent TotalPrice records: {len(mismatches)}")

if len(mismatches) > 0:
    display(mismatches[['quantity', 'unitprice', 'totalprice', 'calculated_totalprice']].head())

#Correct inconsistent TotalPrice values
df.loc[df['totalprice_match'] == False, 'totalprice'] = df['calculated_totalprice']

# Remove helper columns if not needed
df.drop(['calculated_totalprice', 'totalprice_match'], axis=1, inplace=True)

# Save updated dataset
df.to_csv('validated_dataset.csv', index=False)

print("\nDataset validated and saved as 'validated_dataset.csv'")

