# -*- coding: utf-8 -*-
"""Week4(5).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wf0SDvrVmAo9gAv7llcDiXBCvKgizTxP
"""

import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# Load dataset
df = pd.read_csv("/content/final_balanced_dataset.csv")

# Select numerical columns
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns

# Apply Min-Max Normalization
scaler = MinMaxScaler()
df[numerical_cols] = scaler.fit_transform(df[numerical_cols])

print("Numerical data normalized successfully.")

# Create Average Price Per Item
if 'quantity' in df.columns and 'totalprice' in df.columns:
    df['avg_price_per_item'] = df['totalprice'] / df['quantity']

# Create Revenue Segment
if 'totalprice' in df.columns:
    df['revenue_segment'] = pd.qcut(
        df['totalprice'],
        q=3,
        labels=['Low', 'Medium', 'High']
    )

print(df.head())

# Convert InvoiceDate to datetime
if 'invoicedate' in df.columns:
    df['invoicedate'] = pd.to_datetime(df['invoicedate'])

    # Standard format
    df['formatted_date'] = df['invoicedate'].dt.strftime('%Y-%m-%d')
    df['formatted_time'] = df['invoicedate'].dt.strftime('%H:%M:%S')
    print(df[['formatted_date', 'formatted_time']].head())
else:
    print("Column 'invoicedate' not found in DataFrame. Skipping date formatting.")

df.to_csv("final_dataset_processed.csv", index=False)

print("Final processed dataset saved successfully!")