# -*- coding: utf-8 -*-
"""week3(1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_zcKgCsmgTUzaN60-gqOCZ9K0MGO0Gpm
"""

import pandas as pd

# Load dataset
df = pd.read_csv('/content/scaled_encoded_retail_dataset.csv')

#Remove duplicate values

print("Shape before removing duplicates:", df.shape)

df = df.drop_duplicates()

print("Shape after removing duplicates:", df.shape)

#Handling missing values

# Check missing values
print("\nMissing Values Before Handling:")
print(df.isnull().sum())

# Fill numerical columns with mean
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns

for col in numerical_cols:
    df[col].fillna(df[col].mean(), inplace=True)

# Fill categorical columns with mode
categorical_cols = df.select_dtypes(include=['object']).columns

for col in categorical_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

# Check missing values again
print("\nMissing Values After Handling:")
print(df.isnull().sum())

# Save cleaned dataset
df.to_csv('cleaned_retail_dataset.csv', index=False)

print("\nCleaned dataset saved successfully!")



