# -*- coding: utf-8 -*-
"""week3(2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o0wiRNjs_Dgc4CKuz5K7IUqcKQMSlALN
"""

import pandas as pd

# Load dataset
df = pd.read_csv('/content/cleaned_retail_dataset.csv')

#Convert datatype

# Convert InvoiceDate to datetime (if column exists)
if 'InvoiceDate' in df.columns:
    df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

# Convert CustomerID to string
if 'CustomerID' in df.columns:
    df['CustomerID'] = df['CustomerID'].astype(str)

# Convert Quantity and UnitPrice to numeric
if 'Quantity' in df.columns:
    df['Quantity'] = pd.to_numeric(df['Quantity'])

if 'UnitPrice' in df.columns:
    df['UnitPrice'] = pd.to_numeric(df['UnitPrice'])

print("Data Types After Conversion:\n")
print(df.dtypes)

#Remove cancelled orders

# Remove invoices starting with 'C'
if 'InvoiceNo' in df.columns:
    df = df[~df['InvoiceNo'].astype(str).str.startswith('C')]

print("\nShape after removing cancelled orders:", df.shape)

# Save updated dataset
df.to_csv('updated_retail_dataset.csv', index=False)

print("\nUpdated dataset saved successfully!")

